name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files and setup environment
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Build project dependencies
      run: npm run build-release

    - name: List output files
      run: ls

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: wp-content/
        server-dir: www.relictabioplastics.com/wp-content/
        dry-run: true
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          wp-content/themes/relicta/assets/**
          wp-content/themes/plugins/relicta-core/
